export const ModalActionTypes = {
  TOGGLE_MODAL_OPEN: "TOGGLE_MODAL_OPEN",
  SELECT_MODAL_PHONE: "SELECT_MODAL_PHONE",
  SELECT_MODAL_EMAIL: "SELECT_MODAL_EMAIL",
  SELECT_MODAL_RESET: "SELECT_MODAL_RESET",
};
